# Generated by Django 5.2.7 on 2025-11-24 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_listings', to=settings.AUTH_USER_MODEL),
        ),
    ]
