# Generated by Django 5.2.7 on 2025-12-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_buyer_listing_is_sold_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
